services:
  weather-db: 
    build: 
      context: ./weather-db/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data/:/app/data/
    command: ["python3", "main.py"]
    restart: no
    