name: Tests on Microservices

on: [push]

jobs: 
  CI-micro-services:
    runs-on: ubuntu-latest
    steps:
      # SETUP THE ENVIRONMENT
      # Clone the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup the Python and its version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Install the necessary python dependencies
      - name: Python libraries
        run: pip install -r Tests/requirements.txt

      # WEATHER-DB: 
      # Build the container 
      - name: Build the image
        run: docker compose up --build --exit-code-from weather-db
      # Run the Python Tests 
      - name: Run pytest on the generated file
        run: pytest Tests/test_weather-db.py
  
      # WEATHER_DBT :
      # Build dbt models and run dbt tests
      - name: Build the image
        run: docker compose run --build --exit-code-from weather_dbt \
                dbt run ; dbt test
        # Run python tests for database integrity
      - name: Check database integrity
        run: pytest Tests/test_weather_dbt.py